/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PolymarketBotProxy } from "./PolymarketBotProxy";
export type { SubscriptionManager } from "./SubscriptionManager";
