/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PolymarketBotProxy {
  export type TradingConfigStruct = {
    maxTradeSize: BigNumberish;
    dailySpendLimit: BigNumberish;
    spentToday: BigNumberish;
    lastResetDay: BigNumberish;
    isActive: boolean;
    tier: BigNumberish;
  };

  export type TradingConfigStructOutput = [
    maxTradeSize: bigint,
    dailySpendLimit: bigint,
    spentToday: bigint,
    lastResetDay: bigint,
    isActive: boolean,
    tier: bigint
  ] & {
    maxTradeSize: bigint;
    dailySpendLimit: bigint;
    spentToday: bigint;
    lastResetDay: bigint;
    isActive: boolean;
    tier: bigint;
  };
}

export interface PolymarketBotProxyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "USDC"
      | "botWallet"
      | "canTrade"
      | "checkAllowance"
      | "emergencyWithdraw"
      | "executeTrade"
      | "getTierLimits"
      | "getUserConfig"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "revokeTradingAccess"
      | "setTradingConfig"
      | "tierDailyLimit"
      | "tierMaxTradeSize"
      | "transferOwnership"
      | "unpause"
      | "updateBotWallet"
      | "updateTierLimits"
      | "userConfigs"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BotWalletUpdated"
      | "EmergencyWithdraw"
      | "OwnershipTransferred"
      | "Paused"
      | "TierLimitsUpdated"
      | "TradeExecuted"
      | "TradingAccessRevoked"
      | "TradingConfigSet"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(functionFragment: "botWallet", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "canTrade",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkAllowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTrade",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTierLimits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserConfig",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeTradingAccess",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTradingConfig",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tierDailyLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tierMaxTradeSize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateBotWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTierLimits",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userConfigs",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "botWallet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canTrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTierLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeTradingAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTradingConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tierDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tierMaxTradeSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateBotWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTierLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userConfigs",
    data: BytesLike
  ): Result;
}

export namespace BotWalletUpdatedEvent {
  export type InputTuple = [oldWallet: AddressLike, newWallet: AddressLike];
  export type OutputTuple = [oldWallet: string, newWallet: string];
  export interface OutputObject {
    oldWallet: string;
    newWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawEvent {
  export type InputTuple = [
    user: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, token: string, amount: bigint];
  export interface OutputObject {
    user: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TierLimitsUpdatedEvent {
  export type InputTuple = [
    tier: BigNumberish,
    maxTradeSize: BigNumberish,
    dailyLimit: BigNumberish
  ];
  export type OutputTuple = [
    tier: bigint,
    maxTradeSize: bigint,
    dailyLimit: bigint
  ];
  export interface OutputObject {
    tier: bigint;
    maxTradeSize: bigint;
    dailyLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeExecutedEvent {
  export type InputTuple = [
    user: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, token: string, amount: bigint];
  export interface OutputObject {
    user: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradingAccessRevokedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradingConfigSetEvent {
  export type InputTuple = [
    user: AddressLike,
    maxTradeSize: BigNumberish,
    dailyLimit: BigNumberish,
    tier: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    maxTradeSize: bigint,
    dailyLimit: bigint,
    tier: bigint
  ];
  export interface OutputObject {
    user: string;
    maxTradeSize: bigint;
    dailyLimit: bigint;
    tier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PolymarketBotProxy extends BaseContract {
  connect(runner?: ContractRunner | null): PolymarketBotProxy;
  waitForDeployment(): Promise<this>;

  interface: PolymarketBotProxyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  USDC: TypedContractMethod<[], [string], "view">;

  botWallet: TypedContractMethod<[], [string], "view">;

  canTrade: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [[boolean, string]],
    "view"
  >;

  checkAllowance: TypedContractMethod<
    [user: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  executeTrade: TypedContractMethod<
    [user: AddressLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getTierLimits: TypedContractMethod<
    [tier: BigNumberish],
    [[bigint, bigint]],
    "view"
  >;

  getUserConfig: TypedContractMethod<
    [user: AddressLike],
    [PolymarketBotProxy.TradingConfigStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeTradingAccess: TypedContractMethod<[], [void], "nonpayable">;

  setTradingConfig: TypedContractMethod<
    [
      _maxTradeSize: BigNumberish,
      _dailyLimit: BigNumberish,
      _tier: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  tierDailyLimit: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  tierMaxTradeSize: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateBotWallet: TypedContractMethod<
    [_newBotWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  updateTierLimits: TypedContractMethod<
    [
      _tier: BigNumberish,
      _maxTradeSize: BigNumberish,
      _dailyLimit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  userConfigs: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint] & {
        maxTradeSize: bigint;
        dailySpendLimit: bigint;
        spentToday: bigint;
        lastResetDay: bigint;
        isActive: boolean;
        tier: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "botWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "canTrade"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish],
    [[boolean, string]],
    "view"
  >;
  getFunction(
    nameOrSignature: "checkAllowance"
  ): TypedContractMethod<
    [user: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeTrade"
  ): TypedContractMethod<
    [user: AddressLike, token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTierLimits"
  ): TypedContractMethod<[tier: BigNumberish], [[bigint, bigint]], "view">;
  getFunction(
    nameOrSignature: "getUserConfig"
  ): TypedContractMethod<
    [user: AddressLike],
    [PolymarketBotProxy.TradingConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeTradingAccess"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTradingConfig"
  ): TypedContractMethod<
    [
      _maxTradeSize: BigNumberish,
      _dailyLimit: BigNumberish,
      _tier: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tierDailyLimit"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "tierMaxTradeSize"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateBotWallet"
  ): TypedContractMethod<[_newBotWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTierLimits"
  ): TypedContractMethod<
    [
      _tier: BigNumberish,
      _maxTradeSize: BigNumberish,
      _dailyLimit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userConfigs"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint] & {
        maxTradeSize: bigint;
        dailySpendLimit: bigint;
        spentToday: bigint;
        lastResetDay: bigint;
        isActive: boolean;
        tier: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "BotWalletUpdated"
  ): TypedContractEvent<
    BotWalletUpdatedEvent.InputTuple,
    BotWalletUpdatedEvent.OutputTuple,
    BotWalletUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdraw"
  ): TypedContractEvent<
    EmergencyWithdrawEvent.InputTuple,
    EmergencyWithdrawEvent.OutputTuple,
    EmergencyWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "TierLimitsUpdated"
  ): TypedContractEvent<
    TierLimitsUpdatedEvent.InputTuple,
    TierLimitsUpdatedEvent.OutputTuple,
    TierLimitsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TradeExecuted"
  ): TypedContractEvent<
    TradeExecutedEvent.InputTuple,
    TradeExecutedEvent.OutputTuple,
    TradeExecutedEvent.OutputObject
  >;
  getEvent(
    key: "TradingAccessRevoked"
  ): TypedContractEvent<
    TradingAccessRevokedEvent.InputTuple,
    TradingAccessRevokedEvent.OutputTuple,
    TradingAccessRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TradingConfigSet"
  ): TypedContractEvent<
    TradingConfigSetEvent.InputTuple,
    TradingConfigSetEvent.OutputTuple,
    TradingConfigSetEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BotWalletUpdated(address,address)": TypedContractEvent<
      BotWalletUpdatedEvent.InputTuple,
      BotWalletUpdatedEvent.OutputTuple,
      BotWalletUpdatedEvent.OutputObject
    >;
    BotWalletUpdated: TypedContractEvent<
      BotWalletUpdatedEvent.InputTuple,
      BotWalletUpdatedEvent.OutputTuple,
      BotWalletUpdatedEvent.OutputObject
    >;

    "EmergencyWithdraw(address,address,uint256)": TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;
    EmergencyWithdraw: TypedContractEvent<
      EmergencyWithdrawEvent.InputTuple,
      EmergencyWithdrawEvent.OutputTuple,
      EmergencyWithdrawEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "TierLimitsUpdated(uint8,uint256,uint256)": TypedContractEvent<
      TierLimitsUpdatedEvent.InputTuple,
      TierLimitsUpdatedEvent.OutputTuple,
      TierLimitsUpdatedEvent.OutputObject
    >;
    TierLimitsUpdated: TypedContractEvent<
      TierLimitsUpdatedEvent.InputTuple,
      TierLimitsUpdatedEvent.OutputTuple,
      TierLimitsUpdatedEvent.OutputObject
    >;

    "TradeExecuted(address,address,uint256)": TypedContractEvent<
      TradeExecutedEvent.InputTuple,
      TradeExecutedEvent.OutputTuple,
      TradeExecutedEvent.OutputObject
    >;
    TradeExecuted: TypedContractEvent<
      TradeExecutedEvent.InputTuple,
      TradeExecutedEvent.OutputTuple,
      TradeExecutedEvent.OutputObject
    >;

    "TradingAccessRevoked(address)": TypedContractEvent<
      TradingAccessRevokedEvent.InputTuple,
      TradingAccessRevokedEvent.OutputTuple,
      TradingAccessRevokedEvent.OutputObject
    >;
    TradingAccessRevoked: TypedContractEvent<
      TradingAccessRevokedEvent.InputTuple,
      TradingAccessRevokedEvent.OutputTuple,
      TradingAccessRevokedEvent.OutputObject
    >;

    "TradingConfigSet(address,uint256,uint256,uint8)": TypedContractEvent<
      TradingConfigSetEvent.InputTuple,
      TradingConfigSetEvent.OutputTuple,
      TradingConfigSetEvent.OutputObject
    >;
    TradingConfigSet: TypedContractEvent<
      TradingConfigSetEvent.InputTuple,
      TradingConfigSetEvent.OutputTuple,
      TradingConfigSetEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
