/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SubscriptionManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIC_PRICE"
      | "PREMIUM_PRICE"
      | "PRO_PRICE"
      | "SUBSCRIPTION_DURATION"
      | "USDC"
      | "botProxy"
      | "cancel"
      | "getDefaultLimits"
      | "getSubscription"
      | "getTierPrice"
      | "hasActiveSubscription"
      | "owner"
      | "pause"
      | "paused"
      | "renew"
      | "renounceOwnership"
      | "subscribe"
      | "subscriptions"
      | "transferOwnership"
      | "treasury"
      | "unpause"
      | "updateBotProxy"
      | "updateTreasury"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BotProxyUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "SubscriptionCanceled"
      | "SubscriptionPurchased"
      | "SubscriptionRenewed"
      | "TreasuryUpdated"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIC_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PREMIUM_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "PRO_PRICE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "SUBSCRIPTION_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(functionFragment: "botProxy", values?: undefined): string;
  encodeFunctionData(functionFragment: "cancel", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getDefaultLimits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscription",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTierPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasActiveSubscription",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "renew", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "subscribe",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateBotProxy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTreasury",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIC_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PREMIUM_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PRO_PRICE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SUBSCRIPTION_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "botProxy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDefaultLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTierPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasActiveSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "renew", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateBotProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTreasury",
    data: BytesLike
  ): Result;
}

export namespace BotProxyUpdatedEvent {
  export type InputTuple = [oldProxy: AddressLike, newProxy: AddressLike];
  export type OutputTuple = [oldProxy: string, newProxy: string];
  export interface OutputObject {
    oldProxy: string;
    newProxy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCanceledEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionPurchasedEvent {
  export type InputTuple = [
    user: AddressLike,
    tier: BigNumberish,
    amount: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    tier: bigint,
    amount: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    user: string;
    tier: bigint;
    amount: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionRenewedEvent {
  export type InputTuple = [
    user: AddressLike,
    tier: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [user: string, tier: bigint, expiresAt: bigint];
  export interface OutputObject {
    user: string;
    tier: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
  export type OutputTuple = [oldTreasury: string, newTreasury: string];
  export interface OutputObject {
    oldTreasury: string;
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SubscriptionManager extends BaseContract {
  connect(runner?: ContractRunner | null): SubscriptionManager;
  waitForDeployment(): Promise<this>;

  interface: SubscriptionManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIC_PRICE: TypedContractMethod<[], [bigint], "view">;

  PREMIUM_PRICE: TypedContractMethod<[], [bigint], "view">;

  PRO_PRICE: TypedContractMethod<[], [bigint], "view">;

  SUBSCRIPTION_DURATION: TypedContractMethod<[], [bigint], "view">;

  USDC: TypedContractMethod<[], [string], "view">;

  botProxy: TypedContractMethod<[], [string], "view">;

  cancel: TypedContractMethod<[], [void], "nonpayable">;

  getDefaultLimits: TypedContractMethod<
    [tier: BigNumberish],
    [[bigint, bigint] & { maxTradeSize: bigint; dailyLimit: bigint }],
    "view"
  >;

  getSubscription: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, boolean, boolean] & {
        tier: bigint;
        expiresAt: bigint;
        lastPayment: bigint;
        isActive: boolean;
        isExpired: boolean;
      }
    ],
    "view"
  >;

  getTierPrice: TypedContractMethod<[tier: BigNumberish], [bigint], "view">;

  hasActiveSubscription: TypedContractMethod<
    [user: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renew: TypedContractMethod<[], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  subscribe: TypedContractMethod<[tier: BigNumberish], [void], "nonpayable">;

  subscriptions: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        tier: bigint;
        expiresAt: bigint;
        lastPayment: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateBotProxy: TypedContractMethod<
    [_newBotProxy: AddressLike],
    [void],
    "nonpayable"
  >;

  updateTreasury: TypedContractMethod<
    [_newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIC_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PREMIUM_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRO_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SUBSCRIPTION_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "botProxy"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getDefaultLimits"
  ): TypedContractMethod<
    [tier: BigNumberish],
    [[bigint, bigint] & { maxTradeSize: bigint; dailyLimit: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubscription"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, boolean, boolean] & {
        tier: bigint;
        expiresAt: bigint;
        lastPayment: bigint;
        isActive: boolean;
        isExpired: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTierPrice"
  ): TypedContractMethod<[tier: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasActiveSubscription"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renew"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subscribe"
  ): TypedContractMethod<[tier: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subscriptions"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, boolean] & {
        tier: bigint;
        expiresAt: bigint;
        lastPayment: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateBotProxy"
  ): TypedContractMethod<[_newBotProxy: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTreasury"
  ): TypedContractMethod<[_newTreasury: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BotProxyUpdated"
  ): TypedContractEvent<
    BotProxyUpdatedEvent.InputTuple,
    BotProxyUpdatedEvent.OutputTuple,
    BotProxyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCanceled"
  ): TypedContractEvent<
    SubscriptionCanceledEvent.InputTuple,
    SubscriptionCanceledEvent.OutputTuple,
    SubscriptionCanceledEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionPurchased"
  ): TypedContractEvent<
    SubscriptionPurchasedEvent.InputTuple,
    SubscriptionPurchasedEvent.OutputTuple,
    SubscriptionPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionRenewed"
  ): TypedContractEvent<
    SubscriptionRenewedEvent.InputTuple,
    SubscriptionRenewedEvent.OutputTuple,
    SubscriptionRenewedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "BotProxyUpdated(address,address)": TypedContractEvent<
      BotProxyUpdatedEvent.InputTuple,
      BotProxyUpdatedEvent.OutputTuple,
      BotProxyUpdatedEvent.OutputObject
    >;
    BotProxyUpdated: TypedContractEvent<
      BotProxyUpdatedEvent.InputTuple,
      BotProxyUpdatedEvent.OutputTuple,
      BotProxyUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "SubscriptionCanceled(address)": TypedContractEvent<
      SubscriptionCanceledEvent.InputTuple,
      SubscriptionCanceledEvent.OutputTuple,
      SubscriptionCanceledEvent.OutputObject
    >;
    SubscriptionCanceled: TypedContractEvent<
      SubscriptionCanceledEvent.InputTuple,
      SubscriptionCanceledEvent.OutputTuple,
      SubscriptionCanceledEvent.OutputObject
    >;

    "SubscriptionPurchased(address,uint8,uint256,uint256)": TypedContractEvent<
      SubscriptionPurchasedEvent.InputTuple,
      SubscriptionPurchasedEvent.OutputTuple,
      SubscriptionPurchasedEvent.OutputObject
    >;
    SubscriptionPurchased: TypedContractEvent<
      SubscriptionPurchasedEvent.InputTuple,
      SubscriptionPurchasedEvent.OutputTuple,
      SubscriptionPurchasedEvent.OutputObject
    >;

    "SubscriptionRenewed(address,uint8,uint256)": TypedContractEvent<
      SubscriptionRenewedEvent.InputTuple,
      SubscriptionRenewedEvent.OutputTuple,
      SubscriptionRenewedEvent.OutputObject
    >;
    SubscriptionRenewed: TypedContractEvent<
      SubscriptionRenewedEvent.InputTuple,
      SubscriptionRenewedEvent.OutputTuple,
      SubscriptionRenewedEvent.OutputObject
    >;

    "TreasuryUpdated(address,address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
